stages:
  train_model:
    cmd: python3 src/train.py
    deps:
    - data/dataset.csv
    outs:
    - models/model.joblib
  test_model:
    cmd: python src/test.py
    deps:
    - data/dataset.csv
    - models/model.joblib
    outs:
    - results/test_results.txt
  hyperparameter_tuning:
    cmd: python src/train.py
    deps:
    - data/dataset.csv
    outs:
    - models/best_model.joblib
